package scoreboard;

public enum EventType {
    SCORE,
    HOCKEY_GOAL,
    BASKETBALL_FREE_THROW_1_MADE, BASKETBALL_FREE_THROW_2_MADE, BASKETBALL_TWO_POINTER, BASKETBALL_THREE_POINTER,
    FOOTBALL_FIELD_GOAL, FOOTBALL_TOUCHDOWN
}
