INSERT INTO league (name) VALUES ('Aves');
INSERT INTO team (name, league_id) VALUES ('Hummingbird', 1);
INSERT INTO team (name, league_id) VALUES ('Sparrow', 1);
INSERT INTO team (name, league_id) VALUES ('Goldfinch', 1);
INSERT INTO team (name, league_id) VALUES ('Chickadee', 1);
INSERT INTO team (name, league_id) VALUES ('Cardinal', 1);
INSERT INTO team (name, league_id) VALUES ('Oriole', 1);
INSERT INTO team (name, league_id) VALUES ('Robin', 1);
INSERT INTO team (name, league_id) VALUES ('Woodpecker', 1);
INSERT INTO team (name, league_id) VALUES ('Canary', 1);
INSERT INTO team (name, league_id) VALUES ('Bluebird', 1);
INSERT INTO team (name, league_id) VALUES ('Warbler', 1);
INSERT INTO team (name, league_id) VALUES ('Blue Jay', 1);
INSERT INTO team (name, league_id) VALUES ('Purple Martin', 1);
INSERT INTO team (name, league_id) VALUES ('Mourning Dove', 1);
INSERT INTO team (name, league_id) VALUES ('Killdeer', 1);
INSERT INTO team (name, league_id) VALUES ('Mockingbird', 1);
INSERT INTO team (name, league_id) VALUES ('Mallard', 1);
INSERT INTO team (name, league_id) VALUES ('Sea Gull', 1);
INSERT INTO team (name, league_id) VALUES ('Penguin', 1);
INSERT INTO team (name, league_id) VALUES ('Swan', 1);
INSERT INTO team (name, league_id) VALUES ('Flamingo', 1);
INSERT INTO team (name, league_id) VALUES ('Ostrich', 1);
INSERT INTO team (name, league_id) VALUES ('Parrot', 1);
INSERT INTO team (name, league_id) VALUES ('Heron', 1);
INSERT INTO team (name, league_id) VALUES ('Dove', 1);
INSERT INTO team (name, league_id) VALUES ('Eagle', 1);
INSERT INTO team (name, league_id) VALUES ('Owl', 1);
INSERT INTO team (name, league_id) VALUES ('Hawk', 1);
INSERT INTO team (name, league_id) VALUES ('Turkey', 1);
INSERT INTO team (name, league_id) VALUES ('Peacock', 1);
INSERT INTO team (name, league_id) VALUES ('Pelican', 1);
INSERT INTO team (name, league_id) VALUES ('Roadrunner', 1);

INSERT INTO league (name) VALUES ('Test');
INSERT INTO team (name, league_id) VALUES ('TeamA', 2);
INSERT INTO team (name, league_id) VALUES ('TeamB', 2);
INSERT INTO team (name, league_id) VALUES ('TeamC', 2);
INSERT INTO team (name, league_id) VALUES ('TeamD', 2);
INSERT INTO team (name, league_id) VALUES ('TeamE', 2);
INSERT INTO team (name, league_id) VALUES ('TeamF', 2);
INSERT INTO team (name, league_id) VALUES ('TeamG', 2);
INSERT INTO team (name, league_id) VALUES ('TeamH', 2);
INSERT INTO team (name, league_id) VALUES ('TeamI', 2);
INSERT INTO team (name, league_id) VALUES ('TeamJ', 2);
INSERT INTO team (name, league_id) VALUES ('TeamK', 2);
INSERT INTO team (name, league_id) VALUES ('TeamL', 2);
INSERT INTO team (name, league_id) VALUES ('TeamM', 2);
INSERT INTO team (name, league_id) VALUES ('TeamN', 2);
INSERT INTO team (name, league_id) VALUES ('TeamO', 2);
INSERT INTO team (name, league_id) VALUES ('TeamP', 2);
